name: CI process for Workiva/Cobra
on: [push, pull_request]

permissions:
  contents: read
  id-token: write

jobs:
  Wayne-Test-GHA1:
    runs-on: [ self-hosted, small ]
    container: golang:1.20
    steps:
        - uses: actions/checkout@v3
        - name: Unit tests
          run: go test
