name: CI process for Workiva/Cobra
on: [push, pull_request]

permissions:
  contents: read
  id-token: write

jobs:
  Wayne-Test-GHA1:
    runs-on: [ ubuntu-latest ]
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v4
        - name: Unit tests
          run: |
            go version  
            go test
