name: CI

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ 'master' ]
    tags: [ '*' ]

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Test Setup
        run: |
          mkdir test-reports
          go clean -testcache
      - name: Run tests
        run: |
          go test -v 2>&1 `go list ./... | grep -v /vendor/`
#      - name: Upload test results
#        uses: Workiva/gha-upload-test-reports@v2.0.3
#        with:
#          test-reports: "test-reports/unit-test-report.xml"
